---
:year: 2026
:lecture: symbolic_math
:source_html: symbolic_math_hc.html
:glob_extensions: d*/*.html
:public_repository_dir: ../symbolic_math_public
:server_info:
  :ruby_code_dir: c0_mk_stack_dir/bin
  :server_ssh_path: nishitani@ist.ksc.kwansei.ac.jp:~/public_html
  :server_url: https://ist.ksc.kwansei.ac.jp/~nishitani/Lectures
